actionBar:
  # - {sleeping_count}
  # - {candidate_count}
  # - {threshold_count}
  thresholdNotYetReached: '&aEs sind &2{sleeping_count}&a/&2{threshold_count} &abenötigen Spielern im Bett'
  # - {sleeping_count}
  # - {candidate_count}
  # - {threshold_count}
  thresholdReached: '&aDie Nacht wird durchgeschlafen'

chat:
  noCommandPermission: '&7[&5ABSleepMsg&7] &cDir fehlen die Zugriffsrechte für diesen Befehl!'
  # - {command_label}
  commandUsage: '&7[&5ABSleepMsg&7] &cBenutzung: /{command_label} reload'
  configurationReloaded: '&7[&5ABSleepMsg&7] &aDie Konfiguration wurde erneut geladen.'
